services:
  frontend:
    image: "mrksdh/frontend:latest"
    ports:
      - "8080:8080"
    networks:
      - mynet
    environment:
      - "REVIEW_SERVICE=http://reviews:8080"
      - "BOOK_SERVICE=http://booklist:8080"
      - "DETAIL_SERVICE=http://details:8080"
      - "PORT=8080"

  booklist:
    image: "42424242424242424242/bookstore-books:latest"
    networks:
      - mynet
    expose:
      - "8080"
    environment:
      - "PORT=8080"

  details:
    image: "mrksdh/details:latest"
    networks:
      - mynet
    expose:
      - "8080"
    environment:
      - "PORT=8080"

  reviews:
    image: "mrksdh/reviews:latest"
    networks:
      - mynet
    expose:
      - "8080"
    environment:
      - "PORT=8080"

networks:
  mynet: